---
- name: Criar a conta da lista users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: "{{ users }}"
  when: users is defined

- name: Adicionar a chave publica para o usuário gomex
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ users }}"
  when: users is defined

- name: Criar a conta da lista dokku_users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: "{{ dokku_users }}"
  when: dokku_users is defined

- name: Adicionar a chave publica do usuário da lista dokku_users
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ dokku_users }}"
  when: dokku_users is defined

- import_tasks: ssh.yml