---
- name: Instalando o sshd
  apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: Criando /var/run/sshd
  file:
    path: /var/run/sshd
    state: directory
    mode: '0755'

- name: Configurando o sshd
  template:
    src: sshd_config
    dest: /etc/ssh/
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Reiniciar sshd
