---
- name: Instalando o sshd
  package:
    name: openssh-server
    state: present

- name: Criando /var/run/sshd
  file:
    path: /var/run/sshd
    state: directory
    mode: '0755'

- name: Configurando o sshd
  template:
    src: sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -tf %s
  notify:
    - Reiniciar sshd
