---
- name: Instalando o sudo
  package:
    name: sudo
    state: present

- name: Removendo qualquer configuração do grupo sudo no sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^%sudo'
    validate: /usr/sbin/visudo -cf %s
    
- name: Configurando include no sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '#includedir /etc/sudoers.d'
    validate: /usr/sbin/visudo -cf %s

- name: Configurando grupo sudo
  copy:
    src: group_sudo
    dest: /etc/sudoers.d 
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
